services:
  votix:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 5000:5000

    volumes:
      - ./data:/app/app/var
      - ./logs:/app/app/logs

    restart: unless-stopped