version: '3'
services:
  votix:
    build:
      context: docker
    ports:
      - "8000:8000"
    environment:
      YARN_CACHE_FOLDER: /mnt/cache_yarn
      COMPOSER_CACHE_DIR: /mnt/cache_composer
    volumes:
      - .:/srv
      # persistent caches for dependency managers
      - ./var/cache_yarn:/mnt/cache_yarn
      - ./var/cache_composer:/mnt/cache_composer
      # enable xdebug in development for debugging and test coverage
      - ./docker/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    user: ${CURRENT_UID:-1000}:${CURRENT_GID:-1000}