# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # todo default en
    locale: 'fr'

    # This is a random secret used to generate links
    # This must be long and random bytes
    votix_secret: '%env(default:default_votix_secret:base64:VOTIX_SECRET)%'
    default_votix_secret: ThisTokenIsNotSoSecretChangeItInDotEnv

    # This is used as passphrase to encrypt the RSA private key
    # This must be long and preferably ascii
    votix_key_secret: '%env(default:default_votix_key_secret:base64:VOTIX_KEY_SECRET)%'
    default_votix_key_secret: ThisTokenIsNotSoSecretChangeItInDotEnv

    # This is used to access the results, must be communicated to the person who will access the result
    # This must be random but still typable on a keyboard under stress
    votix_result_password: '%env(default:default_votix_result_password:base64:VOTIX_RESULT_PASSWORD)%'
    default_votix_result_password: ThisTokenIsNotSoSecretChangeItInDotEnv

    votix_admin_password: '%env(string:base64:VOTIX_ADMIN_PASSWORD)%'
    env(VOTIX_ADMIN_PASSWORD): "JGFyZ29uMmlkJHY9MTkkbT02NTUzNix0PTQscD0xJFZYbG9NRXRyTXpFeFdXTmhhMjVWZVEkS3BuejRQTU1hOXRZeWNVSWFkWmN5STFKWHo5MDJvKy9EK2VieWpYQ09tQQ=="

    # Hardcoded base for urls sent in emails. Must contain "/vote/"
    votix_link_base: '%env(VOTIX_LINK_BASE)%'
    env(VOTIX_LINK_BASE): https://subdomain.example.com/vote/
  
    # http://www.timestamp.fr/
    votix_start:   '%env(int:VOTIX_START)%'
    votix_end:     '%env(int:VOTIX_END)%'
    votix_support: '%env(VOTIX_SUPPORT)%'

    env(VOTIX_START): 0
    env(VOTIX_END): 1558317580
    env(VOTIX_SUPPORT): votix@domain.tld

    # email parameters
    votix_from: '%env(VOTIX_FROM)%'
    votix_reply_to: '%env(VOTIX_REPLY_TO)%'
    votix_return_path: '%env(VOTIX_RETURN_PATH)%'

    env(VOTIX_FROM): votix@domain.tld
    env(VOTIX_REPLY_TO): votix@domain.tld
    env(VOTIX_RETURN_PATH): votix@domain.tld

    votix_subtitle: '%env(string:VOTIX_SUBTITLE)%'
    env(VOTIX_SUBTITLE): "Élections du BDE"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $votixStart: '%votix_start%'
            $votixEnd: '%votix_end%'
            $keysDirectory: '%kernel.project_dir%/var'
            $secretKey: '%votix_key_secret%'
            $secret: '%votix_secret%'
            $pepper: '%votix_secret%'
            $linkBase: '%votix_link_base%'
            $password: '%votix_result_password%'
            $from: '%votix_from%'
            $replyTo: '%votix_reply_to%'
            $returnPath: '%votix_return_path%'
            $votixSupport: '%votix_support%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
